using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace TCSTest.Swagger
{
    /// <summary>
    /// Removes auto-generated ID fields from Swagger schema definitions
    /// for specific DTOs to simplify request models.
    /// </summary>
    public class HideAutoGeneratedIdSchemaFilter : ISchemaFilter
    {
        private static readonly HashSet<Type> TargetDtoTypes = new()
        {
            typeof(TCSTest.Models.Channel),
            typeof(TCSTest.Models.Content)
        };

        private static readonly HashSet<string> HiddenProperties = new()
        {
            "channelId",
            "contentId"
        };

        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            if (schema?.Properties == null) return;

            if (!TargetDtoTypes.Contains(context.Type)) return;

            foreach (var prop in HiddenProperties)
            {
                if (schema.Properties.ContainsKey(prop))
                {
                    schema.Properties.Remove(prop);
                }
            }
        }
    }
}
